{
 "title": "Jormungandr Monitor",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Jormungandr Block Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jormungandr_lastBlockHeight_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Jormungandr Block Production Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "avg blocks/5m" } },
   "yaxes": [
    { "format": "avg blocks/5m" }
   ],
   "targets": [
    {
     "expr": "avg_over_time((rate(jormungandr_lastBlockHeight_gauge{namespace=\"$namespace\"}[5m]) * 60)[5m])",
     "legendFormat": "{{client_id}}"
    },
    {
     "expr": "avg_over_time((rate(jormungandr_lastBlockHeight_gauge{namespace=~\"catalyst-fund.*\"}[5m]) * 60)[5m])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Jormungandr Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jormungandr_connections_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Jormungandr Last Block Slot",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jormungandr_lastBlockSlot_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Jormungandr Blocks Received Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jormungandr_blockRecvCnt_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Jormungandr Transaction Received Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jormungandr_txRecvCnt_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Process CPU Utilization (1m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg by(client_id) (irate(process_cpu_seconds_total_counter[1m]))) * 100",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Cluster Aggregate Bandwidth (bps)",
   "type": "graph",
   "description": "20 second rolling time average",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "sum(rate(net_bytes_recv{host!=\"monitoring\"}[20s])) * 8",
     "legendFormat": "Aggregate cluster ingress (received)"
    },
    {
     "expr": "sum(rate(net_bytes_sent{host!=\"monitoring\"}[20s]) * -8) ",
     "legendFormat": "Aggregate cluster egress (transmit)"
    }
   ]
  },
  {
   "title": "Jormungandr Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "jormungandr_uptime_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Jormungandr Last Block Epoch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jormungandr_lastBlockEpoch_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Node Bandwidth (bps)",
   "type": "graph",
   "description": "20 second rolling time average",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(net_bytes_recv{host!~\"monitoring\",device!~\"lo\"}[20s]) * 8",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "rate(net_bytes_sent{host!~\"monitoring\",device!~\"lo\"}[20s]) * -8",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "process_open_fds_gauge", "legendFormat": "{{client_id}}" }
   ]
  },
  {
   "title": "Jormungandr Last Block Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jormungandr_lastBlockSum_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Jormungandr Last Block Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    {
     "expr": "jormungandr_lastBlockTime_gauge{namespace=\"$namespace\"} * 1000",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Jormungandr Last Block Fees",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jormungandr_lastBlockFees_gauge{namespace=\"$namespace\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Jormungandr Service Restarts in 1 hr",
   "type": "graph",
   "description": "Jormungandr restarts in a 1 hr rolling window",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "round(increase((jormungandr_uptime_gauge{namespace=\"$namespace\"} > bool 0)[1h]))",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Jormungandr Completed Backup Jobs",
   "type": "graph",
   "description": "Jormungandr completed backups in a 1 hr period",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "jobs/hr" } },
   "yaxes": [
    { "format": "jobs/hr" }
   ],
   "targets": [
    {
     "expr": "increase(sum by (namespace) (nomad_client_allocs_complete_value{job=~\"backup.*\", namespace=\"$namespace\"} default 0)[1h])",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Jormungandr Failed Backup Jobs",
   "type": "graph",
   "description": "Jormungandr failed backups in a 1 hr period",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "fails/hr" } },
   "yaxes": [
    { "format": "fails/hr" }
   ],
   "targets": [
    {
     "expr": "increase(sum by (namespace) (union(nomad_client_allocs_failed_value{job=~\"backup.*\", namespace=\"$namespace\"},0))[1h])",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Cluster Aggregate Data Transfer, 1 hr Rolling Window",
   "type": "graph",
   "description": "/",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
     "legendFormat": "1h Cluster Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{alias!~\"monitoring.*\",device!~\"lo\"}[1h])) * 3600",
     "legendFormat": "1h Cluster Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "Last Block Hash Piece1",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 48 },
   "targets": [
    {
     "expr": "jormungandr_lastBlockHashPiece1_gauge{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Node Memory Available (%)",
   "type": "graph",
   "description": "Counts memory that is free as well as reclaimable from caches and buffers",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{alias!~\"monitoring.*\"} / node_memory_MemTotal_bytes{alias!~\"monitoring.*\"} * 100",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Node Memory Free (%)",
   "type": "graph",
   "description": "Counts only memory that is physically free",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{alias!~\"monitoring.*\"} / node_memory_MemTotal_bytes{alias!~\"monitoring.*\"} * 100",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Faucet Funds (ADA)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jormungandr_address_funds{alias=~\"faucet.*\",namespace=\"$namespace\"} / 1e6",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Faucet Tx Counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jormungandr_address_counts{namespace=\"$namespace\", alias=~\"faucet.*\"}",
     "legendFormat": "{{addr}}"
    }
   ]
  }
 ]
}